/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
#undef JNITest_FOCUS_TRAVERSABLE_UNKNOWN
#define JNITest_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef JNITest_FOCUS_TRAVERSABLE_DEFAULT
#define JNITest_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef JNITest_FOCUS_TRAVERSABLE_SET
#define JNITest_FOCUS_TRAVERSABLE_SET 2L
#undef JNITest_TOP_ALIGNMENT
#define JNITest_TOP_ALIGNMENT 0.0f
#undef JNITest_CENTER_ALIGNMENT
#define JNITest_CENTER_ALIGNMENT 0.5f
#undef JNITest_BOTTOM_ALIGNMENT
#define JNITest_BOTTOM_ALIGNMENT 1.0f
#undef JNITest_LEFT_ALIGNMENT
#define JNITest_LEFT_ALIGNMENT 0.0f
#undef JNITest_RIGHT_ALIGNMENT
#define JNITest_RIGHT_ALIGNMENT 1.0f
#undef JNITest_serialVersionUID
#define JNITest_serialVersionUID -7644114512714619750LL
#undef JNITest_serialVersionUID
#define JNITest_serialVersionUID 4613797578919906343LL
#undef JNITest_INCLUDE_SELF
#define JNITest_INCLUDE_SELF 1L
#undef JNITest_SEARCH_HEAVYWEIGHTS
#define JNITest_SEARCH_HEAVYWEIGHTS 1L
#undef JNITest_OPENED
#define JNITest_OPENED 1L
#undef JNITest_serialVersionUID
#define JNITest_serialVersionUID 4497834738069338734LL
#undef JNITest_DEFAULT_CURSOR
#define JNITest_DEFAULT_CURSOR 0L
#undef JNITest_CROSSHAIR_CURSOR
#define JNITest_CROSSHAIR_CURSOR 1L
#undef JNITest_TEXT_CURSOR
#define JNITest_TEXT_CURSOR 2L
#undef JNITest_WAIT_CURSOR
#define JNITest_WAIT_CURSOR 3L
#undef JNITest_SW_RESIZE_CURSOR
#define JNITest_SW_RESIZE_CURSOR 4L
#undef JNITest_SE_RESIZE_CURSOR
#define JNITest_SE_RESIZE_CURSOR 5L
#undef JNITest_NW_RESIZE_CURSOR
#define JNITest_NW_RESIZE_CURSOR 6L
#undef JNITest_NE_RESIZE_CURSOR
#define JNITest_NE_RESIZE_CURSOR 7L
#undef JNITest_N_RESIZE_CURSOR
#define JNITest_N_RESIZE_CURSOR 8L
#undef JNITest_S_RESIZE_CURSOR
#define JNITest_S_RESIZE_CURSOR 9L
#undef JNITest_W_RESIZE_CURSOR
#define JNITest_W_RESIZE_CURSOR 10L
#undef JNITest_E_RESIZE_CURSOR
#define JNITest_E_RESIZE_CURSOR 11L
#undef JNITest_HAND_CURSOR
#define JNITest_HAND_CURSOR 12L
#undef JNITest_MOVE_CURSOR
#define JNITest_MOVE_CURSOR 13L
#undef JNITest_NORMAL
#define JNITest_NORMAL 0L
#undef JNITest_ICONIFIED
#define JNITest_ICONIFIED 1L
#undef JNITest_MAXIMIZED_HORIZ
#define JNITest_MAXIMIZED_HORIZ 2L
#undef JNITest_MAXIMIZED_VERT
#define JNITest_MAXIMIZED_VERT 4L
#undef JNITest_MAXIMIZED_BOTH
#define JNITest_MAXIMIZED_BOTH 6L
#undef JNITest_serialVersionUID
#define JNITest_serialVersionUID 2673458971256075116LL
#undef JNITest_EXIT_ON_CLOSE
#define JNITest_EXIT_ON_CLOSE 3L
/*
 * Class:     JNITest
 * Method:    getTitleName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_getTitleName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNITest
 * Method:    getLValName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_getLValName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNITest
 * Method:    parseFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNITest_parseFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
